using Entities.Categories;
using Entities.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyDatabase.Seeding
{
    public class SeedingService
    {
        ApplicationDbContext db;
        public SeedingService(ApplicationDbContext context)
        {
            db = context;
        }

        public void SeedBeer()
        {
            BeerCategory bC1 = new BeerCategory() { Kind = "Ale" };
            BeerCategory bC2 = new BeerCategory() { Kind = "Belgian" };
            BeerCategory bC3 = new BeerCategory() { Kind = "Bock" };
            BeerCategory bC4 = new BeerCategory() { Kind = "Lager" };
            BeerCategory bC5 = new BeerCategory() { Kind = "Pilsner" };
            BeerCategory bC6 = new BeerCategory() { Kind = "Porter" };
            BeerCategory bC7 = new BeerCategory() { Kind = "Stout" };
            BeerCategory bC8 = new BeerCategory() { Kind = "Wheat" };

            List<BeerCategory> beerCategories = new List<BeerCategory>() { bC1, bC2, bC3, bC4, bC5, bC6, bC7, bC8 };
            db.BeerCategories.AddRange(beerCategories);

            Beer b1 = new Beer { Name = "Blue Moon", Description = "White Wheat Beer 330ml is brewed with Valencia orange peel for a subtle sweetness and bright, citrus aroma\n(White Wheat 5.4% alcohol)", Price = 2, PhotoUrl = "https://www.drinksupermarket.com/media/catalog/product/cache/0288c1cb4e2e8b328879830e17ef5901/b/l/blue-moon-beer-belgian-white-wheat-beer-single-bottle-5-4-abv_1_1.jpg", Category = bC8 };
            Beer b2 = new Beer { Name = "Moosehead", Description = "Cracked Canoe Lager 355ml pours crystal clear straw with a wispy head. Light graininess in the aroma. Some vegetal notes. The taste is lightly malty with a touch of sweetness \n(Lager 3.5% alcohol)", Price = 2.5, PhotoUrl = "https://www.drinksupermarket.com/media/catalog/product/cache/0288c1cb4e2e8b328879830e17ef5901/m/o/moosehead-cracked-canoe-lager-355ml-can.jpg", Category = bC4 };
            Beer b3 = new Beer { Name = "Andwell Brewing", Description = "Crouch, Hold, Engage Rich Red IPA 500ml has a well-balanced fruity hop profile. Simcoe provides a hint of pink grapefruit to blend with the distinctive gooseberry characteristics of Nelson Sauvin, while Mosaic completes the trio with its tropical notes \n(Red IPA 4,5% alcohol)", Price = 3, PhotoUrl = "https://www.drinksupermarket.com/media/catalog/product/cache/0288c1cb4e2e8b328879830e17ef5901/a/n/andwell-brewing-co-crouch-hold-engage-rich-red-ipa-500ml.jpg", Category = bC1 };
            Beer b4 = new Beer { Name = "Kopparberg", Description = "Kopparberg Rhubarb Cider 500ml infused with rhubarb delivers a truly unique and fruity taste refreshing to the last drop \n(Ale 4% alcohol)", Price = 3, PhotoUrl = "https://cdn.shopify.com/s/files/1/0079/3912/9434/products/straw-and-lime-500_500x.jpg?v=1631694902", Category = bC6 };
            Beer b5 = new Beer { Name = "Guinness Nigerian", Description = "Guinness Nigerian 600ml is also known as Foreign Extra Import and is brewed at the Guinness factory in Nigeria. It features two special ingredients, maize and sorghum, which give this beer an exciting bitter taste \n(Stout 7.5% alcohol)", Price = 3.2, PhotoUrl = "https://www.drinksupermarket.com/media/catalog/product/cache/0288c1cb4e2e8b328879830e17ef5901/g/u/guinness-nigerian-foreign-export-600ml.jpg", Category = bC7 };
            Beer b6 = new Beer { Name = "Bernard", Description = "Bernard Amber Lager 500ml is a typical bohemian lager with a full body and significant hoppy taste, pleasant yeasty character, and moderate carbonation \n(Lager  5,0% alcohol)", Price = 3.2, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/bernard-amber.jpg?w=430&ssl=1", Category = bC4 };
            Beer b7 = new Beer { Name = "Hobgoblin ", Description = "Wychwood Hobgoblin 500ml is a dark ale brewed with Chocolate and Crystal malts, with Styrian, Goldings and Fuggles hops \n(Dark Ale 5,3% alcohol)", Price = 3.6, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/02/Wychwood-Hobgoblin-500ml.jpg?w=500&ssl=1", Category = bC1 };
            Beer b8 = new Beer { Name = "Weihenstephaner", Description = "Weihenstephaner Vitus 500ml is full-bodied and sparkling with an effervescent mouthfeel. Thus, the Vitus does not taste like a typical Bock beer but more like a noble, fruity wheat beer \n(Bock 7,7% alcohol)", Price = 3.4, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/Weihenstephaner-Vitus1.jpg?w=450&ssl=1", Category = bC3 };
            Beer b9 = new Beer { Name = "Warsteiner", Description = "Warsteiner Premium Verum 500ml has a unique, slightly tart taste. Only top quality ingredients are used in the brewing of this beer. The beer is pleasantly light thanks to especially soft brewing water \n(Pilsner 4.8% alcohol)", Price = 3.4, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/Warsteiner-Premium-Verum1.jpg?w=490&ssl=1", Category = bC5 };
            Beer b10 = new Beer { Name = "Voreia", Description = "Voreia Stout 330ml is a singular beer made with 6 different special malts of barley, it has aromas of chocolate, coffee and caramel flavours and strong aftertaste of black chocolate \n(Stout 6,0% alcohol)", Price = 2.8, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/04/Voreia-Stout.jpg?w=500&ssl=1", Category = bC7 };
            Beer b11 = new Beer { Name = "Voreia", Description = "Voreia Smoked Amber Ale 330ml has strong aromas of tobacco, baked caramel, bread and bacon. The taste is soft and sweet at first and the smoke leaves a pleasant aftertaste along with a slight bitterness \n(Amber Ale 7% alcohol)", Price = 2.8, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/04/Voreia-Smoked-Amber-Ale.jpg?w=500&ssl=1", Category = bC1 };
            Beer b12 = new Beer { Name = "Trappistes", Description = "Trappistes Rochefort 10 330ml has the characteristic champaign-like effervescence. Malt forward with darker fruit flavors, caramel \n(Belgian 11.30% alcohol)", Price = 5.20, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/Rochefort-Trappistes-10-331.jpg?w=450&ssl=1", Category = bC2 };
            Beer b13 = new Beer { Name = "Sura", Description = "Sura Blonde Ale 330ml is a smooth beer with clear golden color and a brilliant clarity. A slight residual sweetness keep things balanced with the hop bitterness. The mellow hop varieties keep the hop and fruit aroma low,perfectly harmonized with the rich malt character \n(Blonde Ale 4.2%  alcohol)", Price = 2.90, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/05/Sura-Blonde-Ale.jpg?w=500&ssl=1", Category = bC1 };
            Beer b14 = new Beer { Name = "Strange Brew", Description = "Mandy Black 330ml is a beer in which you can really get a taste of the chocolate and dark roasted cereal  \n(Stout 7% alcohol)", Price = 3.1, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/12/Strange-Brew-Mandy-Black.jpg?w=470&ssl=1", Category = bC7 };
            Beer b15 = new Beer { Name = "Strange Brew", Description = "Hay Joe 330ml originated in Belgium, this beer style was specifically brewed to refresh farmers after a long hot day in the fields. Lemony, dry, thirst-quenching, a tribute to those who work under the sun \n(Ale 5,2% alcohol)", Price = 2.4, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2021/07/Strange-Brew-Hay-Joe-330ml.jpg?resize=500%2C500&ssl=1", Category = bC1 };
            Beer b16 = new Beer { Name = "Stala Rousa", Description = "Stala Rousa Red Irish Ale 330ml is a sterile, unfiltered red Ale with amber-red color. It has a light body and aromas of caramelized malt and grapes \n(Red Irish Ale 5,5% alcohol)", Price = 2.5, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/09/stala-rousa.jpg?w=450&ssl=1", Category = bC1 };
            Beer b17 = new Beer { Name = "St Peter’s", Description = "St Peter’s The Saints Whisky Beer 500ml is a superbly balanced beer golden in appearance with peaty smoky aromas and smooth whisky flavours from peated malt. With a measure of English Whisky from St. George's Distillery in Norfolk, it is rich in flavour and a superb after dinner drink \n(Scotch Ale 4,8% alcohol)", Price = 4.4, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2019/02/St-Peters-The-Saints-Whisky-Beer.jpg?w=500&ssl=1", Category = bC1 };
            Beer b18 = new Beer { Name = "Sknipa", Description = "Sknipa Strong Ale 330ml  is a Strong Ale type of beer from Thessaloniki. It has a deep amber color, creates a tall and rich crown while during serving, the strong aromas of hops, citrus and pine that characterize it stand out \n(Ale 7% alcohol)", Price = 3.0, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/01/Sknipa-Strong-Ale-1.jpg?resize=500%2C500&ssl=1", Category = bC1 };
            Beer b19 = new Beer { Name = "Sierra Nevada", Description = "Sierra Nevada Pale Ale 355ml is a delightful example of the classic pale ale style. It has a deep amber color and a exceptionally full-bodied, complex character. The fragrant bouquet and spicy flavor are the results of the generous use of the best Cascade hops \n(Pale Ale 5,6% alcohol)", Price = 4.2, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/06/Sierra-Nevada-Pale-Ale.jpg?w=500&ssl=1", Category = bC1 };
            Beer b20 = new Beer { Name = "Septem", Description = "Septem Monday’s Pilsner 500ml is a fresh, unpasteurized, filtered beer, with golden-blonde colour and creamy white head. Aromas of lemon blossoms, citrus and “green hops”. Slightly sweet flavour with refreshing bitterness and aromatic aftertaste, where the zesty and malty aromas dominate \n(Pilsner 5% alcohol)", Price = 2.3, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/septem-mon-pilsner.jpg?w=500&ssl=1", Category = bC5 };
            Beer b21 = new Beer { Name = "Schneider Weisse", Description = "Schneider Weisse Aventinus TAP 6 500ml has a sturdy body, which in combination with its sweet malty aroma is an invitation to profound indulgence - an ingenious blend with a strong body. Perfectly matches rustic dishes, dark roasts and sweet desserts \n(Weisse 8,2% alcohol)", Price = 4.2, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/11/Schneider-Weisse-Aventinus.jpg?w=500&ssl=1", Category = bC8 };
            Beer b22 = new Beer { Name = "Schneider Eisbock", Description = "Schneider Aventinus Eisbock 330ml is a dark beer with Spicy flavours of plum, banana and clove reveal themselves along with a hint of bitter almond and marzipan. This is definitely an after dinner beer \n(Bock 12% alcohol)", Price = 5.2, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2019/02/Schneider-Aventinus-Eisbock.jpg?w=500&ssl=1", Category = bC8 };
            Beer b23 = new Beer { Name = "Salonikia", Description = "Salonikia Honey Pilsner 330ml has a deep yellow colour, aromas of malt and flowers, with notes of citrus. Taste rich, with balance of sweet character and bitter aftertaste \n(Pilsner 5.5% alcohol)", Price = 1.9, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/04/Salonikia-Honey-Pilsner.jpg?resize=500%2C500&ssl=1", Category = bC5 };
            Beer b24 = new Beer { Name = "Pilsner Urquell", Description = "Czech Pilsener 500ml has a refreshing crispness from natural carbonation, then subtle caramel tones and a clean finish with a pleasing hoppy bitterness \n(Pilsener 4.4% alcohol)", Price = 2.90, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/Pilsner-Urquell1.jpg?w=470&ssl=1", Category = bC5 };
            Beer b25 = new Beer { Name = "PaulanerWeissbier ", Description = "Paulaner Weissbier 500ml is a naturally cloudy and shining silky-gold in the glass under a really strong head of foam \n(Wheat 5,5% alcohol)", Price = 2.20, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/04/Paulaner-Weissbier.jpg?w=500&ssl=1", Category = bC8 };
            Beer b26 = new Beer { Name = "Kwak Pauwel", Description = "Kwak Pauwel 330ml has earthy aromas, a malty character with touches of liquorice, a nougat-like robustness and a warm finish not unlike caramelised banana. Yeast and red fruits are the strongest aromas, but you will also find a few herbs \n(Belgian 8.4% alcohol)", Price = 4.2, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/kwak11.jpg?w=430&ssl=1", Category = bC2 };
            Beer b27 = new Beer { Name = "Kwak Pauwel", Description = "Kwak Pauwel 750mlhas earthy aromas, a malty character with touches of liquorice, a nougat-like robustness and a warm finish not unlike caramelised banana. Yeast and red fruits are the strongest aromas, but you will also find a few herbs \n(Belgian 8.4% alcohol)", Price = 3.4, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/kwak-751.jpg?w=460&ssl=1", Category = bC2 };
            Beer b28 = new Beer { Name = "Paulaner Salvator", Description = "Paulaner Salvator 330ml has a head in the colour of caramel, while the beer is chestnut brown, combined with a seductive flavour of chocolate to give a pleasing intensity on the palate \n(Bock 7,9% alcohol)", Price = 2.1, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/12/bottle-int-1000x1550-sal.jpg?w=500&ssl=1", Category = bC3 };
            Beer b29 = new Beer { Name = "Ora Weiss", Description = "Ora Weiss 500ml with a taste of wheat, a product of double fermentation, stands out for its fruity taste and refreshing acidity \n(Weiss 5% alcohol)", Price = 2.5, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/04/Ora-Weiss.jpg?w=500&ssl=1", Category = bC8 };
            Beer b30 = new Beer { Name = "Ora Pilsner", Description = "Ora Pilsner 500ml with a subtle malt and light bitterness of a traditional Czech Pils fused with the unmistakable aromas of local Motueka and Nelson Sauvin Hops \n(Pilsner 4,5% alcohol)", Price = 2.2, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/04/Ora-Pilsner.jpeg?w=500&ssl=1", Category = bC5 };
            Beer b31 = new Beer { Name = "Noctua Night Vision", Description = "Noctua Night Vision 330ml is black opaque, unfiltered, with rich beige foam, has clear characteristics of malt, but also notes of mocha and chocolate\n(IPA 7,2% alcohol)", Price = 3.1, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/Noctua-Night-Vision-Black-IPA11.jpg?w=450&ssl=1", Category = bC1 };
            Beer b32 = new Beer { Name = "Noctua Insomnia", Description = "Noctua Insomnia 330ml has a full body and moderate bitterness, perfectly combined with the aromas of citrus, peach and pine \n(India Pale Ale 5,8 % alcohol)", Price = 2.8, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2019/05/Noctua-Insomnia-330ml.jpg?w=500&ssl=1", Category = bC1 };
            Beer b33 = new Beer { Name = "Noctua Head Twister", Description = "Noctua Head Twister 500ml has American hops with citrus, earthy characteristics and cereal create the aroma and taste of this golden pale ale \n(Blonde Ale 5,8% alcohol)", Price = 2.8, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/noctua-head-twister1.jpg?w=450&ssl=1", Category = bC1 };
            Beer b34 = new Beer { Name = "Niki", Description = "Niki Amber Lager 330ml is a unique “hybrid” lager beer with amber color. Three of the finest pale malts combined with large quantities of delicate noble hops \n(Amber Lager  5,5% alcohol)", Price = 2.7, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/02/Kirki-Niki.jpg?w=500&ssl=1", Category = bC4 };
            Beer b35 = new Beer { Name = "Midnight Circus", Description = "Midnight Circus One-Eyed Jack 330ml is a dark blond beer, with malt flavors and tastes, hops, medium body and refreshing aftertaste \n(Lager 6% alcohol)", Price = 2.7, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/04/Midnight-Circus-One-Eyed-Jack.jpg?w=500&ssl=1", Category = bC4 };
            Beer b36 = new Beer { Name = "Maisel’s", Description = "Maisel’s Weisse Original 500ml has a  fresh scent of fine yeast and pleasant fruity notes combine with the mild, spicy aroma of malt, fruit and clove with a touch of nutmeg in the first sip \n(Weisse 5,1% alcohol)", Price = 2.5, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/Maisels-Weisse-Original1.jpg?w=450&ssl=1", Category = bC8 };
            Beer b37 = new Beer { Name = "La Goudale", Description = "La Goudale Blonde 750ml has a gold color, since it is made by yellow fruits, caramelized cereals and herbaceous notes \n(Blonde 7,2% alcohol)", Price = 6.7, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/la-goudale1.jpg?w=450&ssl=1", Category = bC4 };
            Beer b38 = new Beer { Name = "La Chouffe", Description = "La Chouffe Belgian Strong Ale 750ml is deftly camouflaging its deceptive alcohol strength among layers of ripe fruit aromas and honeyed malt \n(Ale 8% alcohol)", Price = 9.0, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/07/La-Chouffe-750ml.jpg?w=500&ssl=1", Category = bC2 };
            Beer b39 = new Beer { Name = "La Bière du Démon", Description = "La Bière du Démon Strong Lager 330ml has an Amber color, with citrus and caramel noted roundness and a sweet flavor \n(Strong Lager 12% alcohol)", Price = 5.1, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2019/12/La-Biere-du-Demon-330ml.jpg?resize=500%2C500&ssl=1", Category = bC4 };
            Beer b40 = new Beer { Name = "Kykao Woody Imperial", Description = "Kykao Woody Imperial IPA 330ml is a truly hop forward West Coast IPA that's all about hops! From aroma to taste to aftertaste it's all about those juice and piney American hops \n(IPA 9.99% alcohol)", Price = 5.3, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/06/Kykao-Woody-Imperial-IPA.jpg?w=500&ssl=1", Category = bC1 };
            Beer b41 = new Beer { Name = "Kykao Oak Aged Barley Wine", Description = "Kykao Oak Aged Barley Wine 330ml, it's warmth and booziness welcomes you in this hearty sweet English Barleywine! Rich caramel malt flavours, toasted marshmallow, dried fruit and a smooth and chewy mouthfeel \n(Oak Aged Barley Wine 12% alcohol)", Price = 6.8, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/06/Kykao-Oak-Aged-Barley-Wine.jpg?w=500&ssl=1", Category = bC2 };
            Beer b42 = new Beer { Name = "Kozel Mistruv Lezak", Description = "Kozel Mistruv Lezak Premium 500ml has aroma of grain, sweet malt, flowers, corn and metal. Medium plus sweetness, light bitterness and moderate body \n(Lager 4,8% alcohol)", Price = 2.4, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/04/Kozel-Mistruv-Lezak.jpg?resize=500%2C500&ssl=1", Category = bC5 };
            Beer b43 = new Beer { Name = "Kozel Velké Popovice", Description = "Kozel Velké Popovice Dark Lager 500ml s characterized by its delicate taste, and is great as a refreshment during the day or to relax with after a job well done \n(Lager 4% alcohol)", Price = 2.5, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/kozel-dark1.jpg?w=450&ssl=1", Category = bC4 };
            Beer b44 = new Beer { Name = "Kloster Scheyern Poculator", Description = "Kloster Scheyern Poculator 500ml is brewed with roasted and pale malts giving it a sweet, roasty flavour but finishes clean due to the lager yeast used \n(Doppelbock Dunkel 7,6% alcohol)", Price = 3.9, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/03/Kloster-Scheyern-Kloster-Doppelbock-Dunkel-1.jpg?w=500&ssl=1", Category = bC3 };
            Beer b45 = new Beer { Name = "Kloster Scheyern", Description = "Kloster-Weisse Hell 500ml is definitely a good example of Bavarian Weissbier. It's a hazy light yellow with very creamy head and good retention \n(Weisse 5,2% alcohol)", Price = 3.3, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/04/Kloster-Scheyern-Kloster-Weisse-Hell.jpg?w=500&ssl=1", Category = bC8 };
            Beer b46 = new Beer { Name = "Kasta Oatmeal Stout", Description = "Kasta Oatmeal Stout 330ml is medium to light bodied, which makes it a very drinkable Oatmeal Stout with roasted malt flavor and light choco-coffee perception. Oatmeal adds a rich and silky character with light sweetness \n(Stout 4,8% alcohol)", Price = 2.9, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/01/Kasta-Oatmeal-Stout.jpg?w=500&ssl=1", Category = bC7 };
            Beer b47 = new Beer { Name = "KastaNew Zealand", Description = "Kasta New Zealand Amber Ale 330ml is a dark copper to light brown ale with flavors of malty caramel, toasted bread and biscuit. It’s on the bitter side with medium body accompanied by light floral -citrus- like aromas \n(Amber Ale 5,9% alcohol)", Price = 2.8, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/01/Kasta-New-Zealand-Amber-Ale.jpg?w=500&ssl=1", Category = bC1 };
            Beer b48 = new Beer { Name = "Kasta American Pale", Description = "Kasta American Pale Ale 330ml is characterized by fruity and citrus-like American hops, this is a low to medium bodied, very drinkable pale ale. Copper to reddish in color with low to medium caramel and toasted maltiness \n(American Pale Ale 5,6% alcohol)", Price = 2.9, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/01/Kasta-American-Pale-Ale.jpg?w=500&ssl=1", Category = bC1 };
            Beer b49 = new Beer { Name = "Kapuziner Kellerweizen", Description = "Kapuziner Kellerweizen 500ml is an amber wheat beer brewed with the finest yeast, giving a top fermented fine note and a pronounced aromatic fruity flavour. It is advised to swirl the bottle before serving \n(Wheat Beer 5.1% alcohol)", Price = 3.8, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/08/Kapuziner-Kellerweizen.jpg?w=500&ssl=1", Category = bC8 };
            Beer b50 = new Beer { Name = "Kapuziner Hefe-Weissbier", Description = "Kapuziner Hefe-Weissbier Naturtrüb 500ml can be described as the dark, top fermented speciality. Typical wheat beer character with a perfect malt-aromatic bouquet \n(Wheat Beer 5.4% alcohol)", Price = 3.4, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/03/Kapuziner-Hefe-Weissbier-Naturtrub.jpg?w=500&ssl=1", Category = bC8 };
            Beer b51 = new Beer { Name = "Innis & Gunn", Description = "Caribbean Rum Cask 330ml, formerly known as Blood Red Sky, casks meet Scottish red beer in an explosion of cool, spicy rum notes, vanilla and rich fruit \n(English Strong Ale 6,8% alcohol)", Price = 3.2, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/11/Innis-and-Gunn-Caribbean-Rum-Cask.jpg?resize=500%2C500&ssl=1", Category = bC1 };
            Beer b52 = new Beer { Name = "Ikariotissa", Description = "Ikariotissa Red Honey Ale 330ml has a light sweetness thanks to the caramelized barley malt and honey. A beer made with water from the natural springs of Ikaria, the island of longevity \n(Honey Red Ale 330ml 5% alcohol)", Price = 2.5, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2019/06/Ikariotissa-Honey-Red-Ale.jpg?w=500&ssl=1", Category = bC1 };
            Beer b53 = new Beer { Name = "Hoegaarden Original White", Description = "Hoegaarden Original White 330ml is  flavored with coriander and orange peel, creating a sweet & sour taste. It is a beer with a refreshing flavor and captivating aroma, unlike any in the world \n(White Ale 4,9% alcohol)", Price = 2.4, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/11/Hoegaarden-Wit-Blanche.jpg?w=500&ssl=1", Category = bC1 };
            Beer b54 = new Beer { Name = "Hertog Jan Dubbel", Description = "Hertog Jan Dubbel 500ml is dark beer with creamy head. Aroma is subtle with maltiness, yeast and floral notes of hops dominant. Flavour is sweet. Alcohol is well-hidden. Finish is slightly sour. It's a full-bodied beer with adequate carbonation \n(Red Ale 7,3% alcohol)", Price = 7.6, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/04/Hertog-Jan-Dubbel1.jpg?w=480&ssl=1", Category = bC1 };
            Beer b55 = new Beer { Name = "HB Schwarze Weisse", Description = "HB Schwarze Weisse 500ml has a harmonious malt-fragrant bouquet, caramel-like, aromatic, gently refreshing and with a velvety soft finish \n(Weisse 5,1% alcohol)", Price = 2.5, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/09/hofbrau-schwarze-weisse.jpg?w=500&ssl=1", Category = bC8 };
            Beer b56 = new Beer { Name = "HB Münchner Weisse", Description = "HB Münchner Weisse 500ml has a distinctive place in the history of Hofbrau Munchen. The beer is characterized by its sparkling, by its rich foam and naturally by its unforgettable refreshing taste \n(Weisse 5,1% alcohol)", Price = 2.6, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/Hofbrau-Munchner-Weisse1.jpg?w=470&ssl=1", Category = bC8 };
            Beer b57 = new Beer { Name = "Guinness Special Export", Description = "Guinness Special Export 330ml has a full-bodied roasted coffee flavour, with bitter chocolate, salty liquorice, molasses and dark fruit accents \n(Foreign Stout 8% alcohol)", Price = 3.8, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/12/Guinness-Special-Export-330ml.jpg?w=500&ssl=1", Category = bC7 };
            Beer b58 = new Beer { Name = "Gouden Carolus", Description = "Cuvée van de Keizer Whisky Infused 750ml was enriched by an infusion of Gouden Carolus Single Malt whisky. The result is a unique beer, powerful and full-bodied, with subtle touches of vanilla, oak and chocolate. \n(Dark special beer 11,7% alcohol)", Price = 16.5, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/06/Gouden-Carolus-Cuv%C3%A9e-van-de-Keizer-Whisky-Infused.jpg?w=500&ssl=1", Category = bC2 };
            Beer b59 = new Beer { Name = "Gouden Carolus", Description = "Cuvée van de Keizer Imperial Dark 750ml has notes of liquorice, plum, dates, and rich esters. Tasting notes include robust plum, liquorice, and rich dark fruits \n(Belgian Strong Dark Ale 11% alcohol)", Price = 13.4, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/12/Gouden-Carolus-Cuv%C3%A9e-van-de-Keizer-Imperial-Dark.jpg?w=500&ssl=1", Category = bC2 };
            Beer b60 = new Beer { Name = "London Pride", Description = "Fuller’s London Pride 500ml has a good malty base with an excellent blend of hop character, resulting in an easy-drinking beer with great body and a fruity, satisfying finish \n(English Bitter 4,7% alcohol)", Price = 4.0, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/London-pride1.jpg?w=480&ssl=1", Category = bC1 };
            Beer b61 = new Beer { Name = "Black Cab", Description = "Fuller’s Black Cab 500ml delivers a rich, full flavour from the chocolate malts in the brew, giving way to a satisfying creamy finish \n(Stout 4,5% alcohol)", Price = 3.4, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/Fullers-Black-Cab1.jpg?w=450&ssl=1", Category = bC7 };
            Beer b62 = new Beer { Name = "Duchesse De Bourgogne", Description = "Duchesse De Bourgogne 750ml is the traditional top fermented reddish-brown ale from the West-Flanders region of Belgium \n(Flanders Red Ale 6,2% alcohol)", Price = 10.3, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2020/10/Duchesse-De-Bourgogne-750ml.jpg?resize=500%2C500&ssl=1", Category = bC1 };
            Beer b63 = new Beer { Name = "Dreamer Crafty Lager", Description = "Dreamer Crafty Lager 330ml is a blonde-yellowish beer, almost clear with floral aromas, lemony taste with spicy notes of green pepper and stong aftertaste of the two excellent hops, Ahtanum and Crystal \n(Lager 4,7% alcohol)", Price = 2.9, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2019/07/Dreamer-Crafty-Lager-btl.jpg?resize=500%2C500&ssl=1", Category = bC4 };
            Beer b64 = new Beer { Name = "Primator 24 Double", Description = "Primator 24 Double 500ml is a unique, difficult to classify into one of the beer categories. Extraordinarily strong dark-garnet beer with a distinctly sweet and full taste \n(Doppelbock 10,5% alcohol)", Price = 2.9, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2018/05/Primator-Double-24.jpg?w=500&ssl=1", Category = bC3 };
            Beer b65 = new Beer { Name = "Weihenstephaner Korbinian", Description = "Weihenstephaner Korbinian 500ml is a full-bodied, dark Doppelbock with light brown foam, wins beer-lovers over with a balance of fruity hints of plums and figs, a dark malt aroma - reminiscent of toffee, nuts and chocolate \n(Doppelbock 7,4% alcohol)", Price = 2.9, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/Weihenstephaner-Korbinian1.jpg?w=450&ssl=1", Category = bC3 };
            Beer b66 = new Beer { Name = "Clepsydra Walnut Pie", Description = "Clepsydra Walnut Pie 330ml has a full body with chocolate, cinnamon, clove & vanilla flavor with subtle notes of orange \n(Imperial Stout 10% alcohol)", Price = 4.2, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2022/02/Clepsydra-Walnut-Pie.jpg?resize=500%2C500&ssl=1", Category = bC7 };
            Beer b67 = new Beer { Name = "Chimay Grande Réserve", Description = "Chimay Grande Réserve 750ml is a dark ale with a powerful aroma. Its complex flavor improves with passing time \n(Belgian Strong Dark Ale 9% alcohol)", Price = 11.1, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2017/03/Chimay-Gr.Reserve.jpg?w=380&ssl=1", Category = bC2 };
            Beer b68 = new Beer { Name = "Carpinus Robust Porter", Description = "Carpinus Robust Porter 330ml is a dark unfiltered beer, with rich body and aromas of coffee, chocolate and vanill \n(Robust Porter 4,9% alcohol)", Price = 4.1, PhotoUrl = "https://i0.wp.com/www.beershop.gr/wp-content/uploads/2021/11/Carpinus-Robust-Porter.jpg?resize=500%2C500&ssl=1", Category = bC6 };
            Beer b69 = new Beer { Name = "Zywiec Porter", Description = "Zywiec Porter 330ml is a dark, strong beer brewed according to the traditional recipe from 1881, with the Munich malt and special malts \n(Porter 9.50% alcohol)", Price = 4.2, PhotoUrl = "https://cdn.shopify.com/s/files/1/0535/5919/7857/products/webbeertemPorter_512x.jpg?v=1614208666", Category = bC6 };
            Beer b70 = new Beer { Name = "Carnegie Porter", Description = "Carnegie Porter has a black body with a small caramel colored head. The aroma is filled with notes of caramel, dark rye bread, and dark chocolate fudge \n(Porter 5.5% alcohol)", Price = 4.5, PhotoUrl = "https://cdn11.bigcommerce.com/s-41e84jdtvf/images/stencil/600x600/products/17498/78551/22114__12602.1613016191.jpg?c=1", Category = bC6 };


            List<Beer> beers = new List<Beer> { b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15, b16, b17, b18, b19, b20, b21, b22, b23, b24, b25, b26, b27, b28, b29, b30, b31, b32, b33, b34, b35, b36, b37, b38, b39, b40, b41, b42, b43, b44, b45, b46, b47, b48, b49, b50, b51, b52, b53, b54, b55, b56, b57, b58, b59, b60, b61, b62, b63, b64, b65, b66, b67, b68, b69, b70 };
            db.Beers.AddRange(beers);
            db.SaveChanges();
        }

        public void SeedWine()
        {
            WineCategory wC1 = new WineCategory() { Kind = "Dessert" };
            WineCategory wC2 = new WineCategory() { Kind = "Red" };
            WineCategory wC3 = new WineCategory() { Kind = "Rose" };
            WineCategory wC4 = new WineCategory() { Kind = "Sparkling" };
            WineCategory wC5 = new WineCategory() { Kind = "Sweet" };
            WineCategory wC6 = new WineCategory() { Kind = "White" };
            List<WineCategory> wineCategories = new List<WineCategory>() { wC1, wC2, wC3, wC4, wC5, wC6 };
            db.WineCategories.AddRange(wineCategories);

            Wine w1 = new Wine { Name = "Cabernario No.8", Description = "Cabernario No.8 Cabernet Sauvignon 2019, 750ml aromas of black fruit with wet-stone, leather and earthy undertones. It's full-bodied with polished tannins. Dusty and layered in the mouth with a round, creamy feel. Slightly earthy \n(14% alcohol)", Price = 21, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h76/h17/13287128170526.png", Category = wC2 };
            Wine w2 = new Wine { Name = "Josh Cellars", Description = "Josh Cellars Cabernet Family Reserve Paso Robles 750ml, this exceptional Cabernet offers an elegant profile of blackcurrant, black cherry, pepper, and vanilla supported by fine tannins. Pair with grilled steak, braised short ribs, lamb stew or mushroom stroganoff \n(14,5% alcohol)", Price = 17.4, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h21/hbe/12705291534366.png", Category =  wC2}; 
            Wine w3 = new Wine { Name = "Olema Pinot Noir", Description = "Olema Pinot Noir Sonoma County 2019, 750ml crushed strawberry, cherry, lemon zest, button-mushroom and cedar aromas. It's medium-bodied with silky tannins and bright acidity. Bright, pure-fruit layers lead to an energetic finish \n(14,2% alcohol)", Price = 23.2 , PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h27/h8c/15986501451806.png", Category = wC2 }; 
            Wine w4 = new Wine { Name = "Oak Ridge Zinfandel", Description = "Oak Ridge Zinfandel Ancient Vine Estate Grown Lodi 2019, 750ml smooth, supple and concentrated, this lavishly fruity and jammy wine coats the palate with blackberry syrup, maple and boysenberry flavors. It's velvety and viscous \n(14% alcohol)", Price = 16.7, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hf2/heb/15986504007710.png", Category = wC2 };
            Wine w5 = new Wine { Name = "Chateau Pierre De Montignac", Description = "Chateau Pierre De Montignac Medoc 2018, 750ml attractive wood-aging flavors and smoothness have polished this wine and given it richness. Blackberry fruits are integrating with the tannins and structure \n(13,5% alcohol)", Price = 22, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/he5/h83/13287125581854.png", Category = wC2 };
            Wine w6 = new Wine { Name = "Le Pont Bandol", Description = "Le Pont Bandol 750ml is one of the smallest appellations in France, produces some exciting wines. This hearty red has notes of cherry, earth and game on the nose, leading into a palate of cassis, plum, spice and flowers. Soft tannins make this an ideal grill wine \n(14 % alcohol)", Price = 26.9, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h19/h70/11464025473054.png", Category = wC2 };
            Wine w7 = new Wine { Name = "Tensley Syrah Santa Barbara", Description = "Tensley Syrah Santa Barbara is inky, extracted and packs a lot of power. Look for intense notes of black pepper and spice as well as rich notes of black plums and berries \n(14% alcohol)", Price = 32.4, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h3c/hfb/8818754093086.png", Category = wC2 };
            Wine w8 = new Wine { Name = "Château d'Yquem", Description = "Chateau D'Yquem Sauternes 2017, 375ml the nose offers intense aromas of fresh and dried apricot and peach pastry, as well as freshly baked creme brulee... Smooth, glossy texture with flavors of grilled orange, dried apricot and an exceptionally long finish \n(14% alcohol)", Price = 220, PhotoUrl = "https://www.totalwine.com/dynamic/x490,375ml/media/sys_master/twmmedia/h8f/h98/15949505691678.png", Category = wC5 };
            Wine w9 = new Wine { Name = "Radius Cabernet", Description = "Radius Cabernet 750ml this delicious Cabernet greets you with aromas of red jammy fruits and black cherry. Hints of toasty oak lead to a delightful finish. A true crowd-pleaser, this is great for entertaining and pairs well with hors d'oeuvres \n(13,5 % alcohol)", Price = 11, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hdc/he8/13287125221406.png", Category = wC2 };
            Wine w10 = new Wine { Name = "Amici Cabernet",Description = "Amici Cabernet Sauvignon Napa 2019, 750ml is deep garnet-purple in color, it charges out of the gate with loads of blueberry preserves & stewed black plums notes on the nose with faint suggestions of redcurrant jelly and rose hip tea plus a waft of wild sage \n(13,4% alcohol)", Price = 54.6, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hea/h69/15078178816030.png", Category = wC2 };
            Wine w11 = new Wine { Name = "Caymus Cabernet", Description = "Caymus Cabernet Sauvignon 2019, 750ml a rich, showy style, with a very creamy texture to its mix of warmed vanilla, plum and boysenberry puree, and melted black licorice flavors. A mocha notes swirls around the fruit on the finish \n(14,5% alcohol)", Price = 95.7, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h1d/ha0/15311794176030.png", Category = wC2 };
            Wine w12 = new Wine { Name = "Donnachiara Taurasi", Description = "Donnachiara Taurasi 2017, 750ml is a very polished, intense aglianico with blackberry, blueberry, rose-stem and wet-earth aromas and flavors. What really impresses is the polished nature of the tannins that caress and massage the palate \n(13,5% alcohol)", Price = 42, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h9e/ha1/11524016603166.png", Category = wC2 };
            Wine w13 = new Wine { Name = "Beau Vigne", Description = "Beau Vigne Cabernet Romeo Napa 2018, 750ml intense dark chocolate covered cherry and roasted coffee glide in on a sleek mouthfeel with seductive notes of blackberry and licorice \n(15,3% alcohol)", Price = 102, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/ha1/h3a/14017177321502.png", Category = wC2 };
            Wine w14 = new Wine { Name = "Samuel Robert Rose", Description = "Samuel Robert Rose Willamette Vintner's Reserve 2020, 750ml the ripe fruit flavors run from strawberry to maraschino cherry to kumquat to marmalade. Extraordinary richness for an inexpensive rose. The lively, spicy finish just doesn't quit \n(13,26% alcohol)", Price = 17.3 , PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hc1/h92/15078178881566.png", Category = wC3 };
            Wine w15 = new Wine { Name = "Olema Rose Cotes De Provence", Description = "Olema Rose Cotes De Provence 2020, 750ml pale rose-gold color. Delicate aromas of white strawberry, rose petal, fresh apricot and lemon cream. It's medium-bodied with bright acidity \n(13% alcohol)", Price = 19.8, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h88/h9c/13287126695966.png", Category = wC3 };
            Wine w16 = new Wine { Name = "Oree Des Roses", Description = "Oree Des Roses 750ml, his pleasant Rose has aromas of red fruit, such as ripe raspberries, wild strawberries, and a reflection of tropical fruit. It is round and delicious on the palate and makes an ideal aperitif. It also pairs well with grilled meats, salads and Asian dishes \n(14,5% alcohol)", Price = 12.3 , PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h6f/h1c/12311745298462.png", Category = wC3 };
            Wine w17 = new Wine { Name = "Olema Rose", Description = "Olema Rose Cotes De Provence Reserve 2020, 750ml is a pale salmon-colored rose with aromas of strawberries, fresh plums, cherry blossom and pomegranates. Medium-to full-bodied with a rich, fruity and flavorful palate \n(13% alcohol)", Price = 26.7, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h6f/h41/14555538718750.png", Category =  wC3};
            Wine w18 = new Wine { Name = "Domaine De Bendel", Description = "Domaine De Bendel Rose Cotes De Provence 750ml, a true gastronomical rose, this wine's palate is balanced, with notes of exotic fruits, citrus, white fruits, and flowers. Enjoy it as an aperitif or paired with lighter dishes \n(13% alcohol)", Price = 24.7, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h3e/h9b/10220247416862.png", Category = wC3 };
            Wine w19 = new Wine { Name = "Marchese Di Borgosol", Description = "Marchese Di Borgosole Rose Puglia IGT 750ml, fresh, varietals aromas that become more complex with time. Very interesting structure due to the balance between soft tannins, acidity and residual sugar. A perfect Italian rose \n(12% alcohol)", Price = 14.5, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h46/hc3/14301443457054.png", Category = wC3 };
            Wine w20 = new Wine { Name = "Chateau Miraval Cotes", Description = "Chateau Miraval Cotes De Provence Rose 2020, 750ml is a rose wine with a soft color and in a shade of rose petal. Elegant, with an aromatic palette reminiscent of fresh summer fruits and floral notes \n(13.5% alcohol)", Price = 23.2, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hb1/hc5/13565720985630.png", Category = wC3 };
            Wine w21 = new Wine { Name = "Salmon Sancerre Rose", Description = "Salmon Sancerre Rose 750ml,is a dry rose from the Pinot Noir grape offers delightful flavors of cherries and strawberries with touches of vanilla in a smooth, elegant style. The perfect match with your favorite salad or fish dish \n(12,5% alcohol)", Price = 27.8, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/he0/h0c/11254749429790.png", Category =  wC3};
            Wine w22 = new Wine { Name = "Courtney Benham", Description = "Courtney Benham Rose Napa 2020, 750ml a medium-bodied Rose with crisp acidity and aromas of strawberry, watermelon, pink grapefruit and stone. Fresh and fruity. Some phenolic tension\n(12,5% alcohol)", Price = 19.7, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h91/hb5/14261367668766.png", Category = wC3 };
            Wine w23 = new Wine { Name = "Etna Rosato", Description = "Scilio Valle Galfina Etna Rosato DOC 750ml is a wine of a brilliant pink hue, with intense, delicate, fruity flavors, and a smooth, structured well balanced taste. This wine pairs well with cheese, sausage and bread \n(13% alcohol)", Price = 26.7, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/he8/h30/11443306758174.png", Category = wC3 };
            Wine w24 = new Wine { Name = "Dark Horse", Description = "Dark Horse Rose 750ml  boasts a refreshingly dry style that explodes with flavors of fresh red fruit, subtle minerality, and a hint of floral which all race toward a bright, crisp finish \n(13% alcohol)", Price = 11, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h5c/hf6/13411422208030.png", Category = wC3 };
            Wine w25 = new Wine { Name = "Borrasca Rose", Description = "Borrasca Rose Cava 750ml with notes of candied strawberries, ripe raspberries, and fragrant pink roses. If you love bubbles like we do, this will be a welcome addition to the table alongside your favorite Prosecco \n(11,5% alcohol)", Price = 13.4, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h99/h2b/12291754524702.png", Category = wC4 };
            Wine w26 = new Wine { Name = "Borrasca Prosecco", Description = "Borrasca Prosecco Rose 750ml bubbly fun in a bottle with tropical and strawberry notes. Never met a charcuterie board or seafood dish it didn't love \n(11% alcohol)", Price = 18.9, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hfc/h3f/15986502107166.png", Category = wC4 };
            Wine w27 = new Wine { Name = "La Vostra", Description = "La Vostra Prosecco Rose 187ml slight cherry and strawberry notes on the nose and palate drive this plush sparkler. Sweet, ripe peach flavor and a zesty character give this wine structure and fun \n(11,5% alcohol)", Price = 7, PhotoUrl = "https://www.totalwine.com/dynamic/x490,187ml/media/sys_master/twmmedia/h03/ha5/14569176793118.png", Category = wC4 };
            Wine w28 = new Wine { Name = "Levert Freres Cremant", Description = "Levert Freres Cremant De Bourgogne Brut Rose 750ml the aromas of red and black fruits dominate this full-bodied Cremant with pleasing acidity. Enjoy as an aperitif or with fruit desserts \n(12% alcohol)", Price = 24.3, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h4e/hf4/13188943577118.png", Category = wC4 };
            Wine w29 = new Wine { Name = "Berberana Gran Tradicion", Description = "Berberana Gran Tradicion Brut Rose Cava 750ml a bold pink color and friendly aromas of stone fruit and red plum get this rose off to a good start. A dry, fresh, citrusy palate is in good shape, while this tastes of orange and snappy red fruits \n(11,5% alcohol)", Price = 14.6, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h97/hfa/8805952290846.png", Category = wC4 };
            Wine w30 = new Wine { Name = "Armani Prosecco", Description = "Armani Prosecco Rose 750ml a green apple background is laced with cherry flavors and a creamy texture that complements the fruit. Dry and soft this well-balanced Prosecco has a round softness to it that opens up to a full-bodied structure \n(11% alcohol)", Price = 21.5, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h2e/h31/14191260270622.png", Category = wC4 };
            Wine w31 = new Wine { Name = "Tissot Maire", Description = "Tissot Maire Cremant Du Jura Rose 750ml this sparkler offers a fresh, expressive nose, with notes of small red berries which explode on the palate. This Cremant is ideal for an entire meal, from appetizers to the dessert \n(12,5% alcohol)", Price = 21.2, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h0d/hce/12071894908958.png", Category = wC4 };
            Wine w32 = new Wine { Name = "Conde De Caralt", Description = "Conde De Caralt Brut Rose Cava 750ml this delicious Rose Cava is bright and transparent with an attractive light strawberry color and an abundant, fine and constant mousse. Fruity aromas reminiscent of raspberry and pomegranate carry through a supple, fruity palate \n(11,5% alcohol)", Price = 14.7, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h65/hbc/8802732802078.png", Category = wC4 };
            Wine w33 = new Wine { Name = "Mascota Vineyards", Description = "Mascota Vineyards La Mascota Brut Rose 750ml attractive cooked apple, toast and brioche character. Medium body, nice balance of fruit and yeast and crisp acidity. Easy to enjoy right now. Limited production. 100% pinot noir made by the champagne method \n(12% alcohol)", Price = 17, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/he5/hcd/10791451230238.png", Category = wC4 };
            Wine w34 = new Wine { Name = "Chandon California", Description = "Chandon California Rose Sparkling Wine 750ml is creamy and seductive, with defined structure from the addition of still Pinot Noir at tirage. The overall impression is one of bold vibrancy and impact from start to finish \n(11% alcohol)", Price = 18.3, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h4f/h23/15311799681054.png", Category = wC4 };
            Wine w35 = new Wine { Name = "Deligeroy Cremant", Description = "Deligeroy Cremant De Loire Rose 750ml made with a touch of Cabernet Franc for color and richness, this Rose sparkler is highlighted by fresh berry and fig notes wrapped by a crisp, palate-cleansing acidity \n(12% alcohol)", Price = 24.6, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h2a/h6f/10140718596126.png", Category = wC4 };
            Wine w36 = new Wine { Name = "Tsarine", Description = "Tsarine Brut Rose NV 750ml with aromas of red fruits with hints of brioche; this Champagne brings layers of fruit and creaminess on palate with bright freshness leading to an elegant finish\n(12% alcohol)", Price = 72, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h0b/h96/9863442923550.png", Category = wC4 };
            Wine w37 = new Wine { Name = "Roederer Estate", Description = "Roederer Estate Brut Rose 750ml crisp peach and red fruit flavors combine with vibrant acidity and energizing fine bubbles to create a balanced and rich sparkling wine. A spicy, crisp fruit character lingers long on the finish \n(11% alcohol)", Price = 29.6, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h0c/h12/13458043043870.png", Category = wC4 };
            Wine w38 = new Wine { Name = "Il Duca Imperiale Moscato", Description = "Il Duca Imperiale Moscato Rose 750ml is filled with fresh flavors of rich nectarine, yellow peach, and wild flower. It can be enjoyed chilled, over ice, or mixed into a delicious and fruity cocktai \n(9,5% alcohol)", Price = 17.6, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hb5/hb0/15421668163614.png", Category = wC4 };
            Wine w39 = new Wine { Name = "Paul Michel", Description = "Paul Michel Brut Rose Premier Cru 750ml a gorgeous salmon pink hue. This Premier Cru rose will start off with a fresh and subtle nose, evoking cherry, strawberry and raspberry flavors after aeration. On the palate you are met with fine and creamy bubbles \n(12,5% alcohol)", Price = 64, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h5f/hea/15166607982622.png", Category = wC4 };
            Wine w40 = new Wine { Name = "Quinta Das Carvalhas", Description = "Quinta Das Carvalhas 10 Year Tawny 750ml a toasty edge, with hazelnut and singed almond notes, while the core of plum cake and cinnamon holds steady through the finish \n(20% alcohol)", Price = 32, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h6f/h2e/14164348993566.png", Category = wC1};
            Wine w41 = new Wine { Name = "Red Decadence Chocolate Wine", Description = "Red Decadence Chocolate Wine 750ml the aromas and flavors of black cherry, blueberry, and plum with touches of rich dark chocolate. The combination of ruby red wine with a natural chocolate core is like a liquid chocolate truffle in a bottle \n(13,5% alcohol)", Price = 13, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h39/h26/11941382979614.png", Category = wC1 };
            Wine w42 = new Wine { Name = "Blue Navarra", Description = "Blue Navarra Moscatel 750ml aromas of fruit are present, followed by flavors of peach, pineapple and other tropical fruit. Easy to drink, this sweet wine is the perfect aperitif or works wonderfully to accompany cheese \n(14,1% alcohol)", Price = 14.5, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h0b/hf1/11770060177438.png", Category = wC1 };
            Wine w43 = new Wine { Name = "Porto Valdouro", Description = "Porto Valdouro Rose 750ml has a vibrant, glittery pink color with reflections of cherry. The bouquet is bursting with aromas of red fruits and the lively palate is filled with flavors of raspberry and cherry with notes of gooseberry \n(19,5% alcohol)", Price = 18.9 , PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hdc/hc8/11339586535454.png", Category = wC1 };
            Wine w44 = new Wine { Name = "Graham's Six Grapes", Description = "Graham's Six Grapes 750ml has a seductive rich perfume of ripe plums and cherries. On the palate, complex, with good structure and a long lingering finish. Best served at the end of the meal, for example with rich, nutty or chocolate desserts, as well as strong cheeses \n(18% alcohol)", Price = 19, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h5b/hbe/12205752647710.png", Category = wC1 };
            Wine w45 = new Wine { Name = "Stella Rosa", Description = "Stella Rosa Black Cherry 750ml has a dark, rich black cherry flavors with an elegant fruit puree similar to the blueberry. Elegant and true black cherry taste \n(5% alcohol)", Price = 12.3, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h21/h20/14323360694302.png", Category = wC1 };
            Wine w46 = new Wine { Name = "Offley Ruby Port", Description = "Offley Ruby Port 750ml sweet red and black fruits dominate the nose and flavor profile of this wonderful dessert wine. This intensely fruity wine is a great way to introduce yourself to the quality of one of the most highly regarded port houses in the world \n(19,5% alcohol)", Price = 17.8, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h48/hb4/8802900082718.png", Category = wC1 };
            Wine w47 = new Wine { Name = "Montonico Port", Description = "Montonico Port 750ml an intensely flavored and moderately sweet fortified wine, offering nutty flavors mixed with fruity aromas such as black currant, plum, caramel and dried red fruits \n(19% alcohol)", Price = 14, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h57/h98/8806108626974.png", Category = wC1 };
            Wine w48 = new Wine { Name = "Don Benigno Fino Sherry", Description = "Don Benigno Fino Sherry 750ml is pale straw in color, light bodied and bone dry with an almond bouquet and refreshing taste, Fino sherry is the lightest and driest of Sherries carrying a delicate, fresh, yeasty flavor with hints of apple \n(15% alcohol)", Price = 13.8, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hb5/h0f/8809253175326.png", Category = wC1 };
            Wine w49 = new Wine { Name = "Chateau Miselle", Description = "Chateau Miselle Sauternes 750ml with it's beautiful golden yellow color invites you to enjoy the delicate and complex bouquet of crystallized apricots, raisins and quinces aromas. This Sauternes is flavorful and intense; its fruity palate is clearly defined and full-bodied \n(13% alcohol)", Price = 27, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h40/h7d/13411422306334.png", Category = wC1 };
            Wine w50 = new Wine { Name = "Courtney Benham", Description = "Courtney Benham Sauvignon Blanc Terroir Selection 750ml is all about finding the best wines throughout California, not limiting to Napa Valley. This crisp and light Sauvignon Blanc is sourced from multiple AVA's within Sonoma County \n(13,1% alcohol)", Price = 15.6, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h14/h07/14814169858078.png", Category = wC6 };
            Wine w51 = new Wine { Name = "King Maui", Description = "King Maui Cellar Reserve Marlborough Sauvignon Blanc 750ml is zesty and bursting with tropical passion fruit and nectarine flavors. It has hints of grass, vibrant acidity and a long, crisp finish. Pairs beautifully with sushi, creamy pasta dishes or a fresh salad \n(12,4% alcohol)", Price = 18.9, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h6d/h9b/15197832249374.png", Category = wC6 };
            Wine w52 = new Wine { Name = "Palliser Estate", Description = "Palliser Estate Sauvignon Blanc has an elegant and finely concentrated style. Tropical fruit and herb flavors are intermixed with a nose that boasts aromas of passionfruit. Hints of minerality and citrus make this wine an exceptional pair with a seafood dish \n(13,7% alcohol)", Price = 24.6, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h40/h53/10791452311582.png", Category = wC6 };
            Wine w53 = new Wine { Name = "Olema Sauvignon", Description = "Olema Sauvignon Blanc Loire 2020, 750ml aromas of grapefruit zest, fresh pear, green papaya and flint. It's medium-bodied with bright, tangy acidity and a gently waxy texture. Fresh finish \n(12% alcohol)", Price = 17.8, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h6f/hbe/13580240158750.png", Category = wC6 };
            Wine w54 = new Wine { Name = "Staete Landt Map Maker", Description = "Staete Landt Map Maker Sauv Blanc 2020, 750ml with herbal aromas of dill and tarragon match with lemon zest. Lime ice is crisp and thrilling on the palate, which opens further dotted by guava and yellow floral tones. Lingers long on the finish \n(13% alcohol)", Price = 18, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h1b/h5e/12033308131358.png", Category = wC6 };
            Wine w55 = new Wine { Name = "Vincent Doucet Sancerre", Description = "Vincent Doucet Sancerre 750ml has a nose of green apple and fresh greenary, with a lifted hint of white blossoms. It's very herbal on the palate, with a green apple and lime peel complexity. This is a perfect match for lobster \n(13% alcohol)", Price = 35, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hb4/h3b/13411423944734.png", Category = wC6 };
            Wine w56 = new Wine { Name = "Singerstone", Description = "Singerstone Sauvignon Blanc 2020, 750ml light and crisp, this delightful white shows its playful side with a zing of grapefruit on the nose and palate. Minerality cools the tongue, with honeyed pear and floral tones following \n(13% alcohol)", Price = 14, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h86/h77/14072350736414.png", Category = wC6 };
            Wine w57 = new Wine { Name = "Cloud Break", Description = "Cloud Break Sauvignon Blanc 750ml has lively flavors of honeydew melon, juicy peach and pear. The aroma is fresh with sweet ripe fruit notes. With its balance of refreshing flavors and smooth, crisp taste this wine pairs great with food \n(12,5% alcohol)", Price = 13, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h8a/h35/12071888322590.png", Category = wC6 };
            Wine w58 = new Wine { Name = "Rothschild Blanc Selection Prestige", Description = "Rothschild Blanc Selection Prestige 750ml is a lively, crisp and dry Sauvignon Blanc, Semillon blend serves up lots of lemon and vanilla flavors with a creamy, smooth finish. Very elegant and classy party wine \n(12% alcohol)", Price = 23 , PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h40/h6c/8809286828062.png", Category = wC6 };
            Wine w59 = new Wine { Name = "Blanchet Pouilly Fume", Description = "Blanchet Pouilly Fume 750ml is light to medium-bodied Sauvignon Blanc features flavors of citrus fruit with a hint of flintiness. Blanchet is a small family-run winery on 8 acres in the heart of Pouilly Fume. This wine pairs well with seafood and salads\n(12,8% alcohol)", Price = 27, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hf0/h00/8818906726430.png", Category = wC6 };
            Wine w60 = new Wine { Name = "Bougrier Pure Loire", Description = "Bougrier Pure Loire Touraine 750ml develops an aromatic, elegant and crisp character with passion fruit and white buds aromas. Pairs beautifully with all fishes, seafood, pork or simply with some goat cheese \n(12,5% alcohol)", Price = 23.6, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h99/h4f/14044485648414.png", Category = wC6 };
            Wine w61 = new Wine { Name = "Third Wheel", Description = "Third Wheel Sweet Red Blend 750ml will surely tickle your palate with its candied sweetness. It presents blackberry bramble, candied cherry and boysenberry flavors. This marvelous medium-bodied wine is bursting with flavor \n(12% alcohol)", Price = 13, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hb7/hdd/11287788978206.png", Category = wC5 };
            Wine w62 = new Wine { Name = "Wilson Creek", Description = "Wilson Creek Sparkling Peach Bellini 750ml, crisp, clean and not overly sweet, this sparkling wine pairs natural peach oils with sparkling wine for the perfect play on a Bellini. Perfect for brunch with friends \n(11% alcohol)", Price = 14.3, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hc5/ha8/12244620869662.png", Category = wC5 };
            Wine w63 = new Wine { Name = "Erica Marlborough", Description = "Erica Marlborough Sauvignon Blanc 2020, 750ml offers bright, fleshy tropical and citrus fruit, apple blossoms and a whisper of green herbs and chalk dust. The palate is nicely textured amidst all that fleshy fruit and tingly acidity \n(13% alcohol)", Price = 28, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h35/h3c/12389155831838.png", Category = wC5 };
            Wine w64 = new Wine { Name = "Romana Sancerre", Description = "Romana Sancerre Blanc 750ml with flavors of peach, pear, and violet. Perfect for seafood or goat cheese from Sancerre in the Loire Valley \n(13% alcohol)", Price = 29, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h53/h23/9411495886878.png", Category = wC5 };
            Wine w65 = new Wine { Name = "Kim Crawford Illuminate", Description = "TKim Crawford Illuminate Sauvignon Blanc 750ml is light in style, full in flavor. It has lifted aromatics of passionfruit and guava, with some citrus notes. Elegant yet full flavored, its crisp acidity is highlighted with a refreshing herbal and citrus finish \n(7% alcohol)", Price = 21, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hbe/hf6/14564169842718.png", Category = wC5 };
            Wine w66 = new Wine { Name = "Villa Maria", Description = "Villa Maria Sauvignon Blanc Private Bin 750ml overflowing with aromas of gooseberry and passionfruit with hints of lime and nettles. The wine is mouth filling with vibrant fruit and mid palate richness, finishing rich and racy with excellent length and crispness \n(12,5% alcohol)", Price = 13.5, PhotoUrl = "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hbb/hca/12939042029598.png", Category = wC5 };

        List<Wine> wines = new List<Wine> { w1, w2, w3, w4, w5,w6 ,w7,w8, w8, w9, w10,w11,w12,w13,w14,w15,w16,w17,w18,w19,w20,w21,w22,w23,w24,w25,w26,w27,w28,w29,w30,w31,w32,w33,w34,w35,w36,w37,w38,w39,w40,w41,w42,w43,w44,w45,w46,w47,w48,w49,w50,w51,w52,w53,w54,w55,w56,w57,w58,w59,w60,w61,w62,w63,w64,w65,w66 };
            db.Wines.AddRange(wines);
            db.SaveChanges();
        }

        public void SeedWhiskey()
        {
            WhiskeyCategory whC1 = new WhiskeyCategory() { Kind = "Blended" };
            WhiskeyCategory whC2 = new WhiskeyCategory() { Kind = "Bourbon" };
            WhiskeyCategory whC3 = new WhiskeyCategory() { Kind = "Canadian" };
            WhiskeyCategory whC4 = new WhiskeyCategory() { Kind = "Japanese" };
            WhiskeyCategory whC5 = new WhiskeyCategory() { Kind = "Irish" };
            WhiskeyCategory whC6 = new WhiskeyCategory() { Kind = "Rye" };
            WhiskeyCategory whC7 = new WhiskeyCategory() { Kind = "Scotch" };
            WhiskeyCategory whC8 = new WhiskeyCategory() { Kind = "Single Malt" };
            WhiskeyCategory whC9 = new WhiskeyCategory() { Kind = "Tennessee" };
            List<WhiskeyCategory> whiskeyCategories = new List<WhiskeyCategory>() { whC1, whC2, whC3, whC4, whC5, whC6, whC7, whC8, whC9 };
            db.WhiskeyCategories.AddRange(whiskeyCategories);
            db.SaveChanges();

        
            Whiskey wh5 = new Whiskey { Name = "GlenDronach", Description = "The GlenDronach Original 12 Year Whisky 70cl", Price = 82, PhotoUrl = "https://cavagreco.gr/image/cache/catalog/products/spirits/whiskey/single%20malt/GlenDronach%2012%20Years%20Old%20Single%20Malt-540x540.jpg", Category = whC1 };
            
            Whiskey wh2 = new Whiskey { Name = "Willett Kentucky Straight", Description = "Willett Kentucky Straight Bourbon Ουίσκι 700ml", Price = 170, PhotoUrl = "https://www.kylix.gr/images/styles/large/02.01.4582.jpg", Category = whC2 };
            Whiskey wh6 = new Whiskey { Name = "Blantons Bourbon Straight From Barrel", Description = "Blantons Bourbon Straight From Barrel Ουίσκι 700ml", Price = 120, PhotoUrl = "https://www.kavakonstantakopoulos.gr/images/thumbs/0000327.jpg", Category = whC2 };
            Whiskey wh7 = new Whiskey { Name = "Evan Williams Bourbon Bottled in Bond", Description = "Evan Williams Bourbon Bottled in Bond Ουίσκι 700ml", Price = 33, PhotoUrl = "https://apostagma.eu/image/cache/catalog/096749021369-2448x3264.jpg", Category = whC2 };
            Whiskey wh8 = new Whiskey { Name = "Knob Creek Small Batch", Description = "Knob Creek Small Batch Ουίσκι Bourbon Patiently Aged 50% 700ml", Price = 42, PhotoUrl = "https://www.akros.gr/media/15518.jpg", Category = whC2 };
            Whiskey wh9 = new Whiskey { Name = "Woodford Reserve Reserve Holiday ", Description = "Woodford Reserve Reserve Holiday Select Ουίσκι Bourbon 43% 700ml", Price = 56, PhotoUrl = "https://www.wine24shop.gr/dat/F129293F/image1_zoom.jpg", Category = whC2 };
            Whiskey wh10 = new Whiskey { Name = "Yellow Rose Outlaw ", Description = "Yellow Rose Outlaw Bourbon Ουίσκι 700ml", Price = 65, PhotoUrl = "https://media02.drankenwereld.be/media/catalog/product/cache/1/image/800x800/70f758824f4feaf2bb853d4989720f7c/y/e/yellow_rose_outlaw_bourbon_whiskey_drankenwereld.jpg", Category = whC2 };
            Whiskey wh11 = new Whiskey { Name = "FEW", Description = "FEW Ουίσκι Bourbon 46.5% 700ml", Price = 70, PhotoUrl = "https://b.scdn.gr/images/sku_main_images/032926/32926467/20211210110454_few_oyiski_bourbon_46_5_700ml.jpeg", Category = whC2 };
            Whiskey wh12 = new Whiskey { Name = "The Balvenie DoubleWood 12 Y.Ο.", Description = "The Balvenie DoubleWood 12 Y.Ο. Ουίσκι Bourbon Από Βαρέλια Virgin Oak 43% 700ml", Price = 62, PhotoUrl = "https://www.woudenbergdranken.nl/beeld/36227/balvenie.american.oak.jpg", Category = whC2 };
            Whiskey wh13 = new Whiskey { Name = "James E. Pepper 1776 Straight", Description = "James E. Pepper 1776 Straight Bourbon 100 Proof Ουίσκι 700ml", Price = 40, PhotoUrl = "https://cdn.shopify.com/s/files/1/0045/4967/3089/products/james_e_pepper_1776_rye_2000x.jpg?v=1595978275", Category = whC2 };
            Whiskey wh14 = new Whiskey { Name = "Buffalo Trace George T Stagg Kentucky Straight", Description = "Buffalo Trace George T Stagg Kentucky Straight Bourbon Ουίσκι 700ml", Price = 170, PhotoUrl = "https://cdn.shopify.com/s/files/1/0173/0930/products/38ca87ab52503f71d111c239f5d6446ab113866d.jpg?v=1619768712", Category = whC2 };
            
            Whiskey wh15 = new Whiskey { Name = "Kinahan's Small Batch ", Description = "Kinahan's Small Batch Ουίσκι Blended Malt 45% 700ml", Price = 34, PhotoUrl = "https://cdn.shopify.com/s/files/1/0269/0183/9966/products/kinahans-small-batch-irish-whiskey-46-abv-0-7l-75349-viski-irlandiya-kupit-viski-kinahans-400_849x.jpg?v=1631777385", Category = whC1 };
            Whiskey wh16 = new Whiskey { Name = "Mackmyra Brukswhisky", Description = "Mackmyra Brukswhisky Blended Malt Ουίσκι 700ml", Price = 47, PhotoUrl = "https://eshop.cavanektar.gr/wp-content/uploads/2020/11/08020350.jpg", Category = whC1 };
            Whiskey wh17 = new Whiskey { Name = "Johnnie Walker Black Label Islay Origin", Description = "Johnnie Walker Black Label Islay Origin Ουίσκι Blended Malt 47% 700ml", Price = 40, PhotoUrl = "https://delhidutyfree.co.in/pub/media/catalog/product/cache/fc260a2b26538f7a220ac21cbf347203/2/0/2002298_1.jpg", Category = whC1 };
            Whiskey wh18 = new Whiskey { Name = "Loch Lomond Reserve", Description = "Loch Lomond Reserve Blended Malt Ουίσκι 700ml", Price = 25, PhotoUrl = "https://static.specsonline.com/wp-content/uploads/2020/10/081406502046.jpg", Category = whC1 };
            Whiskey wh19 = new Whiskey { Name = "Spencerfield Spirit Sheep Dip", Description = "Spencerfield Spirit Sheep Dip Blended Malt Ουίσκι 200ml", Price = 16, PhotoUrl = "https://apostagma.eu/image/cache/catalog/089744761477-3120x3120.jpg", Category = whC1 };
            Whiskey wh20 = new Whiskey { Name = "Douglas Laing Rock Island Sherry Edition", Description = "Douglas Laing Rock Island Sherry Edition Ουίσκι Blended Malt 46.8% 700ml", Price = 80, PhotoUrl = "https://web-whisky-live.s3-eu-west-1.amazonaws.com/s3fs-public/styles/uc_product_full/public/DSC00002_5.JPG?itok=p8rtHcXD", Category = whC1 };
            Whiskey wh21 = new Whiskey { Name = "Kamiki Sakura & Cedar ", Description = "Kamiki Sakura & Cedar Ουίσκι Blended Malt 48% 500ml", Price = 70, PhotoUrl = "https://bigbarrel.co.nz/content/images/thumbs/005/0059944_kamiki-sakura-wood-48-sakura-tree-cedar-cask-finish-japanese-whisky-500ml.jpeg", Category = whC1 };
            Whiskey wh22 = new Whiskey { Name = "Douglas Laing Big Peat Peatrichor Edition", Description = "Douglas Laing Big Peat Peatrichor Edition Ουίσκι Blended Malt 53.8% 700ml", Price = 56, PhotoUrl = "https://whisky.my/cdn-cgi/image/width=1000,height=1000,fit=crop,quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/Big-peat-1.jpg", Category = whC1 };
            Whiskey wh23 = new Whiskey { Name = "Famous Grouse 12 Years Old", Description = "Famous Grouse 12 Years Old Blended Malt Ουίσκι 700ml", Price = 40, PhotoUrl = "https://www.dreamworksdutyfree.com/wp-content/uploads/2018/09/FAMOUS-GROUSE-GOLD-RESERVE-12-YEARS-OLD-1L.jpg", Category = whC1 };
            Whiskey wh24 = new Whiskey { Name = "Spencerfield Spirit Feathery ", Description = "Spencerfield Spirit Feathery Blended Malt Whisky Ουίσκι 200ml", Price = 40, PhotoUrl = "https://cdn2.whiskyworld.de/produkt/the-feathery-blended-malt-whisky-bm-f1100.tif?h=420&w=420&s=822626b48d3f79b6bf26fdf225715955", Category = whC1 };
            
            Whiskey wh25 = new Whiskey { Name = "Stalk & Barrel Blue Blend", Description = "Stalk & Barrel Blue Blend Canadian Whisky 750ml", Price = 30, PhotoUrl = "http://fountaindelivery.com/wp-content/uploads/2019/10/cq5dam.web_.1280.1280-1316.jpeg", Category = whC3 };
            Whiskey wh26 = new Whiskey { Name = "Canadian Club 6 Year Old ", Description = "Canadian Club 6 Year Old Distilled 1967 Bot.1970s", Price = 90, PhotoUrl = "https://img.thewhiskyexchange.com/900/brbon_can53.jpg", Category = whC3 };
            Whiskey wh27 = new Whiskey { Name = "Canadian Club 100% Rye  ", Description = "Canadian Club 100% Rye 750ml ABV: 40% ", Price = 25, PhotoUrl = "https://cdn.caskers.com/catalog/product/cache/ce56bc73870585a38310c58e499d2fd4/c/a/canadian-club-100_-rye01.jpg", Category = whC3 };
            Whiskey wh28 = new Whiskey { Name = "Lot 40 Canadian Rye Whisky", Description = "Lot 40 Canadian Rye Whisky 750ml", Price = 40, PhotoUrl = "https://bigkmarketliquor.com/wp-content/uploads/2020/11/Lot-40-Canadian-Rye-Whisky-600x720.jpg", Category = whC3 };
            Whiskey wh29 = new Whiskey { Name = "Gibson's Finest 12-year-old", Description = "Gibson's Finest 12-year-old Canadian Whisky 750ml ", Price = 25, PhotoUrl = "https://static.specsonline.com/wp-content/uploads/reload/008366487255.jpg", Category = whC3 };
            Whiskey wh30 = new Whiskey { Name = "Canadian Club 43 Year", Description = "Canadian Club 43 Year Canadian Whisky 750ml ", Price =45, PhotoUrl = "https://orders.newsfilecorp.com/files/7294/66586_canadianclub.jpg", Category = whC3 };
            Whiskey wh31 = new Whiskey { Name = "Canadian Club 12-year-old", Description = "Canadian Club 12-year-old 750ml ", Price =25, PhotoUrl = "https://www.binnys.com/globalassets/catalogs/binnys/13/1313/131351/131351.jpg?width=1000&height=1000&mode=BoxPad&bgcolor=fff", Category = whC3 };
            Whiskey wh32 = new Whiskey { Name = "Canadian Club Original 1858", Description = "Canadian Club Original 1858 700ml ", Price =20, PhotoUrl = "https://www.connosr.com/image/2/750/750/2/images/products/canadian-club-classic-12-year-old-9017.jpg", Category = whC3 };
            Whiskey wh33 = new Whiskey { Name = "Canadian Ltd Canadian", Description = "Canadian Ltd Canadian Whisky 1.75L ", Price =15, PhotoUrl = "https://cdn.powered-by-nitrosell.com/product_images/26/6463/large-185230-a.jpg", Category = whC3 };
            Whiskey wh34 = new Whiskey { Name = "Crown Royal", Description = "Crown Royal Canadian Whiskey 750 ml ", Price =25, PhotoUrl = "https://applejack.com/site/images/Crown-Royal-Canadian-Whiskey-750-ml_1.png", Category = whC3 };
            
            Whiskey wh1 = new Whiskey { Name = "The Busker", Description = "The Busker Triple Cask Triple Smooth Irish Whiskey 70cl", Price = 20, PhotoUrl = "https://nutsaboutwine.ie/wp-content/uploads/2021/03/the-busker-single-malt.jpg", Category = whC5 };
            Whiskey wh3 = new Whiskey { Name = "Proclamation", Description = "Proclamation Blended Irish Whiskey 70cl", Price = 27, PhotoUrl = "https://d2wwnnx8tks4e8.cloudfront.net/images/app/large/5391534150329_3.JPG", Category = whC5 };
            Whiskey wh35 = new Whiskey { Name = "The Sexton ", Description = "The Sexton Irish Whiskey", Price = 40, PhotoUrl = "https://www.kylix.gr/images/styles/large/02.01.4424.jpg", Category = whC5 };
            Whiskey wh36 = new Whiskey { Name = "Slane  ", Description = "Slane Irish Whiskey 750ml", Price = 40, PhotoUrl = "https://cdn.whiskyshop.com/media/catalog/product/cache/2e26a3c2dde6ca2e925d95b5afe00706/s/l/slane_ss_1.jpg", Category = whC5 };
            Whiskey wh37 = new Whiskey { Name = "Teeling Small Batch ", Description = "Teeling Small Batch Irish Whiskey 750ml", Price = 30, PhotoUrl = "https://www.rrselection.com/cache/thumbs/5aedc7671509df213b9907a4/0x0-none/rr_selection_Teeling_Whiskey_Small_Batch_Rum_Cask_Finish_darilna_skatla.jpg", Category = whC5 };
            Whiskey wh38 = new Whiskey { Name = "Knappogue Castle 16 Year Old Single Malt", Description = "Knappogue Castle 16 Year Old Single Malt Irish Whiskey 700ml", Price = 100, PhotoUrl = "https://www.comptoir-irlandais.com/5913-thickbox_default/knappogue-castle-16-years-old.jpg", Category = whC5 };
            Whiskey wh39 = new Whiskey { Name = "Green Spot Single Pot Still", Description = "Green Spot Single Pot Still Whiskey 70cl 700ml", Price = 50, PhotoUrl = "https://cdn.shopify.com/s/files/1/1771/5883/products/gs.png?v=1611027862", Category = whC5 };
            Whiskey wh40 = new Whiskey { Name = "McConnell’s", Description = "McConnell’s Irish Whiskey700ml", Price = 100, PhotoUrl = "https://www.binnys.com/globalassets/catalogs/binnys/10/1011/101122/101122.jpg?width=690&height=690&mode=BoxPad&bgcolor=fff", Category = whC5 };
            Whiskey wh41 = new Whiskey { Name = "Jameson", Description = "Jameson Irish Whiskey 700ml", Price = 21, PhotoUrl = "https://www.houseofwine.gr/how/pub/media/catalog/product/cache/04a61031f3eed06cbf15d459d0b61ca5/6/4/647-jameson.jpg", Category = whC5 };
            Whiskey wh42 = new Whiskey { Name = "Roe & Co", Description = "Roe & Co Irish Whiskey Ουίσκι 700ml", Price = 100, PhotoUrl = "https://www.thanopoulos.gr/754078/roe-co-irish-whiskey-ouiski-blended-dublin-700ml.jpg", Category = whC5 };
            
            Whiskey wh43 = new Whiskey { Name = "Yamazaki 12 year old", Description = "yamazaki 12 year old Japanese whisky 700ml", Price = 220, PhotoUrl = "https://www.cavatheodoridis.gr/images/uploads/YAMAZAKIIIIIIIIIIIIII.jpg", Category = whC4 };
            Whiskey wh44 = new Whiskey { Name = "Hakushu 12 Year", Description = "Hakushu 12 Year Japanese whisky 700ml", Price = 250, PhotoUrl = "https://www.kylix.gr/images/styles/large/02.01.3172.jpeg", Category = whC4 };
            Whiskey wh45 = new Whiskey { Name = "Hibiki ", Description = "Hibiki Japanese Harmony Whisky 700ml", Price = 130, PhotoUrl = "https://ngt.gr/wp-content/uploads/2021/11/suntory_distillery_hibiki_japanese_harmony_700ml.jpeg", Category = whC4 };
            Whiskey wh46 = new Whiskey { Name = "Hatozaki", Description = "Hatozaki Japanese Whiskey 700ml", Price = 35, PhotoUrl = "https://assets.gy.digital/ZdunR6eoC4_YXCXYGY3SLYHkkAo=/x/filters:fill(white)/s3.gy.digital%2Fanthidis_gr%2Fuploads%2Fasset%2Fdata%2F9392%2F45225.jpg", Category = whC4 };
            Whiskey wh47 = new Whiskey { Name = "Nikka coffey grain", Description = "nikka coffey grain whisky 750ml", Price = 65, PhotoUrl = "https://www.kavakonstantakopoulos.gr/images/thumbs/0000370.jpg", Category = whC4 };
            Whiskey wh48 = new Whiskey { Name = "Yamazaki 18 Year Old Single Malt", Description = "Yamazaki 18 Year Old Single Malt Japanese Whisky 750ml", Price = 650, PhotoUrl = "https://www.houseofwine.gr/how/pub/media/catalog/product/cache/04a61031f3eed06cbf15d459d0b61ca5/y/a/yamazaki18.jpg", Category = whC4 };
            Whiskey wh49 = new Whiskey { Name = "Akashi White Oak", Description = "Akashi White Oak Japanese Blended Whisky 750ml", Price = 50, PhotoUrl = "https://forwhiskeylovers.com/sites/default/files/styles/uc_product_full/public/store/akashi-white-oak-japanese-whisky-1.jpg?itok=5RZSs_fm", Category = whC4 };
            Whiskey wh50 = new Whiskey { Name = "Kamiki Cedar Cask", Description = "Kamiki Cedar Cask Japanese Whisky 750ml", Price = 49, PhotoUrl = "https://www.tabaccheriatoto13.com/23351-home_default/kamiki-japanese-blended-malt-whisky-cedar-casks-vol48-cl50.jpg", Category = whC4 };
            Whiskey wh51 = new Whiskey { Name = "Sensei", Description = "Sensei Whiskey Japanese  750ml", Price = 40, PhotoUrl = "https://cdn.shopify.com/s/files/1/0425/4092/5091/products/image_0696b939-d4bd-4a20-b42c-32f07aa85891_large.jpg?v=1638176299", Category = whC4 };
            Whiskey wh52 = new Whiskey { Name = "Matsui Sakura Cask Single", Description = "Matsui Sakura Cask Single MaltWhiskey Japanese  750ml", Price = 130, PhotoUrl = "https://cavagreco.gr/image/cache/catalog/products/spirits/whiskey/single%20malt/Matsui%20Sakura-1080x1080.jpg", Category = whC4 };
            
            Whiskey wh53 = new Whiskey { Name = "Hochstadter's Slow & Low", Description = "Hochstadter's Slow & Low Rock and Rye  750ml", Price = 22, PhotoUrl = "https://cdn11.bigcommerce.com/s-e8559/images/stencil/1280x1280/products/7811/7963/hochstadters-slow-and-low-rock-and-rye-whiskey__89285.1529690393.jpg?c=2", Category = whC6 };
            Whiskey wh54 = new Whiskey { Name = "Jim Beam", Description = "Jim Beam Rye Whiskey   750ml", Price = 22, PhotoUrl = "https://cdn.webshopapp.com/shops/7950/files/342904841/650x750x2/jim-beam-jim-beam-rye.jpg", Category = whC6 };
            Whiskey wh55 = new Whiskey { Name = "Angel's Envy Rum Cask Rye", Description = "Angel's Envy Rum Cask Rye Whiskey  750ml", Price = 90, PhotoUrl = "https://cdn.caskers.com/catalog/product/cache/ce56bc73870585a38310c58e499d2fd4/a/n/angel_s-envy-rye-1.jpg", Category = whC6 };
            Whiskey wh56 = new Whiskey { Name = "Rittenhouse", Description = "rittenhouse rye whiskey 750ml", Price = 40, PhotoUrl = "https://d3r6kbofdnmd8.cloudfront.net/media/catalog/product/cache/image/1536x/a4e40ebdc3e371adff845072e1c73f37/1/0/101138_rittenhouse_rye_700_nl_3.jpg", Category = whC6 };
            Whiskey wh57 = new Whiskey { Name = "Sazerac ", Description = "Sazerac Rye Whiskey 750ml  750ml", Price = 27, PhotoUrl = "https://uptownspirits.com/wp-content/uploads/2021/10/Sazerac-Rye-Whiskey-750ml-1.jpg", Category = whC6 };
            Whiskey wh58 = new Whiskey { Name = "Hudson Ny", Description = "Hudson Ny Rye Whiskey   750ml", Price = 42, PhotoUrl = "https://citywinecellar.com/media/catalog/product/cache/9d26d59329362867a375d7ebcb87e847/0/8/083664874514.jpg", Category = whC6 };
            Whiskey wh59 = new Whiskey { Name = "WhistlePig 15 Year", Description = "WhistlePig 15 Year Rye Whiskey 750ml", Price = 90, PhotoUrl = "https://www.drinksupermarket.com/media/catalog/product/cache/0288c1cb4e2e8b328879830e17ef5901/w/h/whistlepig-15yo-vermont-rye-whiskey-750ml_temp.jpg", Category = whC6 };
            Whiskey wh60 = new Whiskey { Name = "Barrell Seagrass ", Description = "Barrell Seagrass Rye Whiskey 750ml", Price = 75, PhotoUrl = "https://norfolkwineandspirits.com/wp-content/uploads/2021/04/barrell-seagrass-rye-whiskey-1000x1000-1.jpg", Category = whC6 };
            Whiskey wh61 = new Whiskey { Name = "FEW Straight ", Description = "FEW Straight Rye Whiskey 750ml", Price = 50, PhotoUrl = "https://cdn.caskers.com/catalog/product/cache/ce56bc73870585a38310c58e499d2fd4/f/e/few-straight-rye-whiskey-1.jpg", Category = whC6 };
            Whiskey wh62 = new Whiskey { Name = "Wilderness Trail", Description = "Wilderness Trail Rye Whiskey 750ml", Price = 70, PhotoUrl = "https://cdn.shopify.com/s/files/1/0404/4898/3190/products/Untitleddesign-2021-01-07T135748.889_1250x.png?v=1610339669", Category = whC6 };

            Whiskey wh4 = new Whiskey { Name = "Johnnie Walker", Description = "Johnnie Walker Blue Label Scotch  Whisky 70cl 2.0 Icons Bottle", Price = 110, PhotoUrl = "https://www.malts.com/en-gb/static/794771079f7422e1fc94398e2a9a83bb/f08e8/5000267187204_Johnnie_Walker_Blue_Label_700ml_Icon_Bottle_CF_1_4b3feef4b1.jpg", Category = whC7 };
            Whiskey wh63 = new Whiskey { Name = "Laphroaig 10 Year Old Islay Single Malt", Description = " Laphroaig 10 Year Old Islay Single Malt Scotch Whisky 750ml", Price = 60, PhotoUrl = "https://cdn11.bigcommerce.com/s-e6b77/images/stencil/1280x1280/products/17062/17422/laphroaig-10-year-old-islay-single-malt-scotch__84406.1607774460.jpg?c=2", Category = whC7 };
            Whiskey wh64 = new Whiskey { Name = "The Famous Grouse", Description = " The Famous Grouse Scotch Whisky 750ml", Price = 20, PhotoUrl = "https://thepartysource.com/image/cache/catalog/inventory/FAMOUS-GROUSE-BLENDED-SCOTCH-750-ML-500x500.jpg", Category = whC7 };
            Whiskey wh65 = new Whiskey { Name = "Johnnie Walker Double Black Label", Description = " Johnnie Walker Double Black Label Blended Scotch Whisky 750ml", Price = 35, PhotoUrl = "https://d2j6dbq0eux0bg.cloudfront.net/images/64027105/2553508905.jpg", Category = whC7 };
            Whiskey wh66 = new Whiskey { Name = "Ardbeg  Uigeadail ", Description = " Ardbeg  Uigeadail Scotch Whisky 750ml", Price = 100, PhotoUrl = "https://cdn2.bigcommerce.com/server5500/tpbc2s65/products/3165/images/3318/ardbeg_corryvreckan750__77792.1366400925.1280.1280.jpg?c=2", Category = whC7 };
            Whiskey wh67 = new Whiskey { Name = " The Macallan Sherry Oak 12 Year Old", Description = " The Macallan Sherry Oak 12 Year Old Single Malt Scotch Whisky 750ml", Price = 70, PhotoUrl = "https://cdn.shopify.com/s/files/1/0227/0581/products/Macallan-12-Year-Old-Sherry-Oak-Scotch-Whisky-750ML-BTL_6_600x.jpg?v=1644151337", Category = whC7 };
            Whiskey wh68 = new Whiskey { Name = "Johnnie Walker High", Description = "Johnnie Walker High Rye Blended Scotch Whisky 750ml", Price = 35, PhotoUrl = "https://www.binnys.com/globalassets/catalogs/binnys/12/1233/123319/123319.jpg?width=690&height=690&mode=BoxPad&bgcolor=fff", Category = whC7 };
            Whiskey wh69 = new Whiskey { Name = "Shackleton", Description = " Shackleton Blended Malt Scotch Whisky 750ml", Price = 35, PhotoUrl = "https://www.marketviewliquor.com/mm5/graphics/00000001/SHACKLETONSCOTCH.jpg", Category = whC7 };
            Whiskey wh70 = new Whiskey { Name = "Grant's Family Reserve", Description = "Grant's Family Reserve Scotch Whisky 750ml", Price = 16, PhotoUrl = "https://www.thewhiskyworld.com/images/grants-family-reserve-p1389-15276_image.jpg", Category = whC7 };
            Whiskey wh71 = new Whiskey { Name = "Royal Salute 21 Year", Description = " Royal Salute 21 Year Scotch Whisky 750ml", Price = 150, PhotoUrl = "https://www.stansliquor.com/wp-content/uploads/2021/09/image_a4b8a9da-9625-4435-a49f-10230afb7b77_1024x1024.jpg", Category = whC7 };




            List<Whiskey> whiskeys = new List<Whiskey> { wh1, wh2, wh3, wh4, wh5,wh6,wh7,wh8,wh9,wh10,wh11,wh12,wh13,wh14,
                                                         wh15,wh16,wh17,wh18,wh19,wh20,wh21,wh22,wh23,wh24,
                                                         wh25,wh26,wh27,wh28,wh29,wh30,wh31,wh32,wh33,wh34,
                                                         wh35,wh36,wh37,wh38,wh39,wh40,wh41,wh42,
                                                         wh43,wh44,wh45,wh46,wh47,wh48,wh49,wh50,wh51,wh52,
                                                         wh53,wh54,wh55,wh56,wh57,wh58,wh59,wh60,wh61,wh62,
                                                         wh63,wh64,wh65,wh66,wh67,wh68,wh69,wh70,wh71};

            db.Whiskeys.AddRange(whiskeys);
            db.SaveChanges();
        }

        public void SeedSpirit()
        {
            SpiritCategory sC1 = new SpiritCategory() { Kind = "Brandy" };
            SpiritCategory sC2 = new SpiritCategory() { Kind = "Gin" };
            SpiritCategory sC3 = new SpiritCategory() { Kind = "Rum" };
            SpiritCategory sC4 = new SpiritCategory() { Kind = "Vodka" };
            List<SpiritCategory> spiritCategories = new List<SpiritCategory>() { sC1, sC2, sC3, sC4 };
            db.SpiritCategories.AddRange(spiritCategories);

            Spirit s1 = new Spirit { Name = "Ciroc", Description = "Ciroc Summer Citrus Vodka 70cl", Price = 32, PhotoUrl = "https://www.drinksupermarket.com/media/catalog/product/cache/0288c1cb4e2e8b328879830e17ef5901/c/i/ciroc-summer-citrus-vodka-70cl_2.jpg", Category = sC4 };
            Spirit s2 = new Spirit { Name = "Grace O'Malley", Description = "Grace O'Malley Heather Infused Irish Gin 70cl", Price = 27, PhotoUrl = "https://cdn.shopify.com/s/files/1/0575/4142/7381/products/GraceO_MalleyHeatherInfusedIrishGin70cl_600x.png?v=1636813382", Category = sC2 };
            Spirit s3 = new Spirit { Name = "Black Thistle", Description = "Black Thistle London Dry Gin 70cl", Price = 25, PhotoUrl = "https://www.drinksupermarket.com/media/catalog/product/cache/0288c1cb4e2e8b328879830e17ef5901/b/l/black-thistle-london-dry-gin-70cl.jpg", Category = sC2 };
            Spirit s4 = new Spirit { Name = "Bush Rum", Description = "Bush Rum Original Spiced Rum 70cl", Price = 27, PhotoUrl = "https://www.ocado.com/productImages/527/527016011_0_640x640.jpg?identifier=afc0efa6b1c816a4315eba0bd71e35ae", Category = sC3 };
            Spirit s5 = new Spirit { Name = "Laplandia", Description = "Laplandia Espresso Vodka 20cl", Price = 10, PhotoUrl = "https://www.drinksupermarket.com/media/catalog/product/cache/0288c1cb4e2e8b328879830e17ef5901/l/a/laplandia-espresso-shot-vodka-70cl_temp.jpg", Category = sC4 };
            Spirit s6 = new Spirit { Name = "Remy Martin X.O", Description = "Remy Martin X.O CRISTALLO 0,7LT", Price = 35, PhotoUrl = "https://static1.s123-cdn-static-a.com/uploads/1087315/800_5aea22d00fb66.jpg", Category = sC1 };
            Spirit s7= new Spirit { Name = "Ed Hardy", Description = "Ed Hardy Βότκα 40% 1000ml", Price = 78, PhotoUrl = "https://d3r6kbofdnmd8.cloudfront.net/media/catalog/product/cache/image/1536x/a4e40ebdc3e371adff845072e1c73f37/9/8/98541_ed-hardy-vodka-10l-40-vol.jpg", Category = sC4 };
            Spirit s8= new Spirit { Name = "Serkova", Description = "Serkova Βότκα 700ml", Price = 14, PhotoUrl = "https://s1.sklavenitis.gr/images/1600x1600/1/files/ProductMedia/Products/2327237/1.jpg", Category = sC4 };
            Spirit s9= new Spirit { Name = "Absolut", Description = "Absolut Βότκα 500ml", Price = 14, PhotoUrl = "https://d3hz4baxchepgp.cloudfront.net/medias/sys_master/h8b/hec/8832233537566.jpg", Category = sC4 };
            Spirit s10= new Spirit { Name = "Absolut Cirton", Description = "Absolut Cirton Βότκα 700ml", Price = 14, PhotoUrl = "https://www.gourmetencasa-tcm.com/15206/absolut-citron-1l.jpg", Category = sC4 };
            Spirit s11= new Spirit { Name = "Diwisa Trojka Black Liqueur", Description = "Diwisa Trojka Black Liqueur Βότκα 700ml", Price = 18, PhotoUrl = "https://www.e-alfasigma.gr/image/cache/data/POTA/VODKA/TROJKA/3376564_001-1100x1100.jpg", Category = sC4 };
            Spirit s12= new Spirit { Name = "Stolichnaya Citros", Description = "Stolichnaya Citros Βότκα 700ml", Price = 18, PhotoUrl = "http://www.absoluteliquorstore.com.sg/images/source/Vodka/Stolichnaya_Stoli_Citros_Vodka_-_700ml.jpg", Category = sC4 };
            Spirit s13= new Spirit { Name = "Belvedere", Description = "Belvedere Βότκα 700ml", Price = 38, PhotoUrl = "https://eshop.cavanektar.gr/wp-content/uploads/2020/10/09010102.jpg", Category = sC4 };
            Spirit s14= new Spirit { Name = "Beluga", Description = "Beluga Βότκα 700ml", Price = 34, PhotoUrl = "https://www.vintagecava.gr/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/b/e/beluga-700ml.jpg", Category = sC4 };
            Spirit s15= new Spirit { Name = "Absolut Elyx", Description = "Absolut Elyx Βότκα 700ml", Price = 43, PhotoUrl = "https://www.vintagecava.gr/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/a/b/absolut-elyx-700ml_1.jpg", Category = sC4 };
            Spirit s16= new Spirit { Name = "Tanqueray ", Description = "Tanqueray London Dry Τζιν 47% 700ml", Price = 22, PhotoUrl = "https://eshop.cavanektar.gr/wp-content/uploads/2020/10/10010002.jpg", Category = sC2 };
            Spirit s17= new Spirit { Name = "Hendrick's", Description = "Hendrick's Gin 700ml", Price = 33, PhotoUrl = "https://static.wixstatic.com/media/5aaf03_6aeaa65d38fb41979aba1fe3f22a2895~mv2.jpg/v1/fill/w_800,h_800,al_c,q_85/5aaf03_6aeaa65d38fb41979aba1fe3f22a2895~mv2.jpg", Category = sC2 };
            Spirit s18= new Spirit { Name = "Etsu Handcrafted", Description = "Etsu Handcrafted Τζιν 700ml", Price = 34, PhotoUrl = "https://www.cavarokos.gr/image/cache/catalog/product/5127-1200x1200.jpg", Category = sC2 };
            Spirit s19= new Spirit { Name = "Schwarzwald Monkey ", Description = "Schwarzwald Monkey 47 Dry Τζιν 500ml", Price = 40, PhotoUrl = "https://d3hz4baxchepgp.cloudfront.net/medias/sys_master/h24/h55/9290153328670.jpg", Category = sC2 };
            Spirit s20= new Spirit { Name = "Bombay Sapphire Distillery", Description = "Bombay Sapphire Distillery Τζιν 700ml", Price = 22, PhotoUrl = "http://www.gowine.gr/media/catalog/product/cache/1/thumbnail/600x600/9df78eab33525d08d6e5fb8d27136e95/1/0/105-96000.jpg", Category = sC2 };
            Spirit s21= new Spirit { Name = "Tanqueray Flor De Sevilla", Description = "Tanqueray Flor De Sevilla Τζιν 700ml", Price = 22, PhotoUrl = "https://s1.sklavenitis.gr/images/ProductDetail/1/files/ProductMedia/Products/1522551/1.jpg", Category = sC2 };
            Spirit s22= new Spirit { Name = "Beefeater Pink ", Description = "Beefeater Pink Τζιν 700ml", Price = 20, PhotoUrl = "https://d3hz4baxchepgp.cloudfront.net/medias/sys_master/h2a/h5a/9286644400158.jpg", Category = sC2 };
            Spirit s23= new Spirit { Name = "Silent Pool", Description = "Silent Pool Τζιν 700ml", Price = 45, PhotoUrl = "https://www.oinognosia.wine/wp-content/uploads/2019/08/silent-pool-gin.jpg", Category = sC2 };
            Spirit s24= new Spirit { Name = "Ron Barcelo Imperial", Description = "Ron Barcelo Imperial Ρούμι 700ml", Price = 27, PhotoUrl = "https://www.e-alfasigma.gr/image/cache/data/POTA/ROUMI/RON%20BARCELO/Ron-Barcelo-Imperial-1100x1100.jpeg", Category = sC3 };
            Spirit s25= new Spirit { Name = "Don Papa Baroko", Description = "Don Papa Baroko Ρούμι 700ml", Price = 43, PhotoUrl = "https://www.kavakonstantakopoulos.gr/images/thumbs/0002711.jpg", Category = sC3 };
            Spirit s26= new Spirit { Name = "Captain Morgan Spiced Gold", Description = "Captain Morgan Spiced Gold Ρούμι 700ml", Price = 16, PhotoUrl = "https://oldcellar.gr/image/cache/catalog/products/%CE%A1%CE%9F%CE%A5%CE%9C%CE%99/20150209085207_18061904-orig-800x800h.jpg.webp", Category = sC3 };
            Spirit s27= new Spirit { Name = "Bacardi Carta Blanca", Description = "Bacardi Carta Blanca Ρούμι 700ml", Price = 18, PhotoUrl = "https://www.thanopoulos.gr/882272/bacardi-roumi-leuko-1lt.jpg", Category = sC3 };
            Spirit s28= new Spirit { Name = "Ron Millonario XO Reserva Especial ", Description = "Ron Millonario XO Reserva Especial Ρούμι 700ml", Price = 108, PhotoUrl = "https://www.akros.gr/media/17515.jpg", Category = sC3 };
            Spirit s29= new Spirit { Name = "Eminente Reserva 7 Year Old ", Description = "Eminente Reserva 7 Year Old Ρούμι 700ml", Price = 52, PhotoUrl = "https://www.akros.gr/media/29422.jpg", Category = sC3 };
            Spirit s30= new Spirit { Name = "Diplomatico Planas", Description = "Diplomatico Planas Ρούμι 700ml", Price = 30, PhotoUrl = "https://www.kylix.gr/images/styles/large/02.01.4142.jpg", Category = sC3 };
            Spirit s31= new Spirit { Name = "Matusalem Insolito ", Description = "Matusalem Insolito Ρούμι 40% 700ml", Price = 41, PhotoUrl = "https://www.gourmetencasa-tcm.com/17177-large_default/matusalem-insolito-wine-cask-limited-edition-70cl.jpg", Category = sC3 };
            Spirit s32= new Spirit { Name = "Flor De Cana 4 Year Old Extra Seco", Description = "Flor De Cana 4 Year Old Extra Seco Ρούμι 700ml", Price = 20, PhotoUrl = "https://www.akros.gr/media/25955.jpg", Category = sC3 };
            Spirit s33= new Spirit { Name = "Καλλικούνης Alexander X.O.", Description = "Καλλικούνης Alexander X.O. Brandy 700ml", Price = 30, PhotoUrl = "https://drink-shop.gr/wp-content/uploads/2019/02/kalikouni-xo-600x600.jpg", Category = sC1};
            Spirit s34= new Spirit { Name = "Vecchia Romagna", Description = "Vecchia Romagna Brandy 700ml", Price =25, PhotoUrl = "https://themaltbar.gr/tmb/wp-content/uploads/2018/08/Vecchia-Romagna.jpg", Category = sC1};
            Spirit s35= new Spirit { Name = "Bache Gabrielsen Tre Kors", Description = "Bache Gabrielsen Tre Kors Brandy 700ml", Price =35, PhotoUrl = "https://static.cognac-expert.com/7526-large_default/bache-gabrielsen-vs-cognac-3-kors-fine.jpg", Category = sC1};
            Spirit s36= new Spirit { Name = "Metaxa Grand Fine ", Description = "Metaxa Grand Fine (Κεραμικό) Brandy 700ml", Price =50, PhotoUrl = "https://drink-shop.gr/wp-content/uploads/2019/10/metaxa_grand_fine_keramiko_brandy_700ml.jpeg", Category = sC1};
            Spirit s37= new Spirit { Name = "Pierre Ferrand 10 Generations ", Description = "Pierre Ferrand 10 Generations, Κονιάκ, 500ml", Price =40, PhotoUrl = "https://d3r6kbofdnmd8.cloudfront.net/media/catalog/product/cache/image/1536x/a4e40ebdc3e371adff845072e1c73f37/1/0/103507_pierre-ferrand-10-generations-cognac-05l-46-vol.jpg", Category = sC1};
            Spirit s38= new Spirit { Name = "Barsol Pisco Primero Quebranta", Description = "Barsol Pisco Primero Quebranta, Μπράντυ, 700ml", Price =31, PhotoUrl = "https://www.e-alfasigma.gr/image/cache/data/APOSTAGMATA/BARSOL/BARSOL-600x600.jpg", Category = sC1};
            Spirit s39= new Spirit { Name = "Remy Martin Louis XIII", Description = "Remy Martin Louis XIII Μπράντυ, 700ml", Price =95, PhotoUrl = "https://atmliquors.com/wp-content/uploads/2020/07/Remy-Martin-Louis-XIIIx-600x600.jpg", Category = sC1};
            
            List<Spirit> spirits = new List<Spirit> { s1, s2, s3, s4, s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,
                                                      s16,s17,s18,s19,s20,s21,s22,s23,s24,s25,s26,s27,s28,s29,s30,s31,s32,
                                                      s33,s34,s35,s36,s37,s38,s39};
            db.Spirits.AddRange(spirits);
            db.SaveChanges();
        }
    }
}
